default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gites_les_celestins_development

test:
  <<: *default
  database: gites_les_celestins_test

production:
  <<: *default
  database: gites_les_celestins_production
  username: leman
  password: q3v9qe2p69r46ufzjf
