development:
  secret_key_base: de131bab527e59d8373cbe396576ad927c20a8331eda6b69c1518294f8a2cb6ddc112500603e82207b9c650c4b0212403b22f05ce629fcbb3878d2ce1910cd54

test:
  secret_key_base: de131bab527e59d8373cbe396576ad927c20a8331eda6b69c1518294f8a2cb6ddc112500603e82207b9c650c4b0212403b22f05ce629fcbb3878d2ce1910cd54

production:
  secret_key_base: de131bab527e59d8373cbe396576ad927c20a8331eda6b69c1518294f8a2cb6ddc112500603e82207b9c650c4b0212403b22f05ce629fcbb3878d2ce1910cd54
